GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9obiIsImlhdCI6MTc2NDY1NzU5MH0.8ZI_QqvfdWoFfPH6NLZcqmrjYWD5uXXMUhYtlTsFYKQ


###

POST http://localhost:3000/login
Content-Type: application/json 

{
    "username": "john"
}

###


POST http://localhost:3000/signup
Content-Type: application/json 

{
    "username": "vivek",
    "password": "vivek123"
}

### 

POST http://localhost:3000/login 
Content-Type: application/json 

{
    "username": "vivek",
    "password": "vivek123"
}

### 

GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidml2ZWsiLCJpZCI6IjY5MmU4ZmM1OTRlMjQ1NTk1Y2ZmOTA1ZSIsImlhdCI6MTc2NDY1OTIyMSwiZXhwIjoxNzY0NjYyODIxfQ.74HawTcCdwAMpRdwwdVGPHI4IoJj73Z2Hbs1dDfRVRU